## Module 4: Data Structure Assignment

In [43]:
"""
1. Create a list named ‘myList’ that is having the following elements: 10,20,30,’apple’, True, 8.10.
    a. Now in the ‘myList’, append these values: 30,40
    b. After that reverse the elements of the ‘myList’ and store that in ‘reversedList’
"""

import numpy as np

my_list = [10,20,30,'apple', True, 8.10]
print("List: ",my_list)

my_list.append(30)
my_list.append(40)
print("\nAfter appending: ", my_list)

np_list=np.array(my_list)
reversedList = np.flip(np_list)
print("\nReversed List: ",reversedList)

List:  [10, 20, 30, 'apple', True, 8.1]

After appending:  [10, 20, 30, 'apple', True, 8.1, 30, 40]

Reversed List:  ['40' '30' '8.1' 'True' 'apple' '30' '20' '10']


In [80]:
"""
2. Create a dictonary with key values as 1,2,3 and the values as ‘data’,’information’, and ‘text’.
    a. After that eliminate the ‘text’ value form the dictonary.
    b. Add ‘features’ in the dictonary.
    c. Fetch the ‘data’ element from the dictonary and display it in the output.
"""

my_dict = {1: 'data',
          2: 'information',
          3: 'text'}
print("Dictionay: ", my_dict)

my_dict[3] = 'features'
print("\nDictionay after updating: ",my_dict)

value='data'
for key, val in my_dict.items():
    if val == value:
        print("Key: ",key)


Dictionay:  {1: 'data', 2: 'information', 3: 'text'}

Dictionay after updating:  {1: 'data', 2: 'information', 3: 'features'}
Key:  1


In [6]:
"""
3. Create a tuple and add these elements 1,2,3,apple,mango in ‘my_tuple
"""

my_tuple=(1,2,3,'apple','mango')
print("My Tuple: ",my_tuple)

My Tuple:  (1, 2, 3, 'apple', 'mango')


In [13]:
"""
4. Create another tuple named numeric_tuple consisting of only integer values 10,20,30,40,50
    a. Find the minimum value from the numeric_tuple.
    b. Concatenate my_tuple with numeric_tuple and store the result in r1.
    c. Duplicate the tuple named my_tuple 2 times and store that in ‘newdupli’.
"""

numeric_tuple =(10,20,30,40,50)
min_value = min(numeric_tuple)
print("min_value",min_value)

r1 = my_tuple + numeric_tuple
print("Result", r1)

newdupli = my_tuple * 2
print("New Tuple: ", newdupli)

min_value 10
Result (1, 2, 3, 'apple', 'mango', 10, 20, 30, 40, 50)
New Tuple:  (1, 2, 3, 'apple', 'mango', 1, 2, 3, 'apple', 'mango')


In [18]:
"""
5. Create 2 sets with name set1 and set2, where set1 contains{1,2,3,4,5} and set2 to contains{2,3,7,6,1}
    a. Perform the below operation:
        a. set1 union set2
        b. set1 intersection set2
        c. set1 difference set2
"""

set1 = {1,2,3,4,5}
set2 = {2,3,7,6,1}

setUnion = set1.union(set2)
print("Union set: ", setUnion)

setIntersection = set1.intersection(set2)
print("Intersection: ", setIntersection)

setDifference = set1 - set2
print("Difference: ",setDifference )

Union set:  {1, 2, 3, 4, 5, 6, 7}
Intersection:  {1, 2, 3}
Difference:  {4, 5}


## Module 4: Numpy Assignment

In [26]:
"""
1. Create a 3x3 matrix array with values ranging from 2 to 10.
"""
import numpy as np
arr=np.arange(2,11)
print("Array 1D: \n",arr)

arr1=np.reshape(arr,(3,3))
print("\n\nArray 3D: \n", arr1)


Array 1D: 
 [ 2  3  4  5  6  7  8  9 10]


Array 3D: 
 [[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [37]:
"""
2. Create a numpy array having user input values and convert the integer type to the float type of the 
elements of the array. For instance:
Original array [1, 2, 3, 4] Array converted to a float type: [ 1. 2. 3. 4.]
"""

def arr():
    n=int(input("How many numbers to be inserted into Array: "))
    i=0
    arr=[]
    for i in range(n):
        x=int(input("Enter Number: "))
        arr.append(x)
    arrInt=np.array(arr)
    print("Int Array: \n",arrInt)
    arrfloat=arrInt.astype(float)
    print("\nFloat Array: \n",arrfloat)

In [38]:
arr()

How many numbers to be inserted into Array: 6
Enter Number: 1
Enter Number: 2
Enter Number: 3
Enter Number: 4
Enter Number: 5
Enter Number: 6
Int Array: 
 [1 2 3 4 5 6]

Float Array: 
 [1. 2. 3. 4. 5. 6.]


In [11]:
"""
3. Write a Numpy program to append values to the end of an array. For instance:
Original array: [10, 20, 30] After append values to the end of the array: [10 20 30 40 50 60 70 80 90]
"""

import numpy as np
original_array = np.array([10,20,30])
append_array = np.array ([10, 20, 30, 40, 50, 60, 70, 80, 90])
original_array=np.append(original_array,append_array)
print(original_array)

[10 20 30 10 20 30 40 50 60 70 80 90]


In [14]:
"""
4. Create two numpy arrays and add the elements of both the arrays and store the result in sumArray.
"""
arr1 = np.array([[1,2,3],
               [4,5,6]])

arr2 = np.array([[7,8,9],
               [4,5,6]])

sumArray = arr1 + arr2
print(sumArray)

[[ 8 10 12]
 [ 8 10 12]]


In [15]:
"""
5. Create a 3*3 array having values from 10-90(interval of 10) and store that in array1. Perform the following tasks:
    a. Extract the 1st row from the array.
    b. Extract the last element from the array.
"""
import numpy as np
arr = np.arange(10,100,10)
array1 = arr.reshape((3,3))
print("3X3 Array: \n",array1)

first_row = array1[0:1]
print("\n First Row: ",first_row)

last_ele=array1[2:3,2:3]
print("\n Last Element: ",last_ele)

3X3 Array: 
 [[10 20 30]
 [40 50 60]
 [70 80 90]]

 First Row:  [[10 20 30]]

 Last Element:  [[90]]


## Module 4: Numpy Assignment

In [1]:
"""
1. Create a function that takes dimensions as tuples e.g.(3, 3) and a numeric value and returns a Numpy 
array of the given dimension filled with the given value e.g.: solve((3, 3), 5) will return
[ [5, 5, 5], [5, 5, 5], [5, 5, 5] ]
"""

import numpy as np
def fun1(dimention, value):
    return np.full(dimention,value)

In [3]:
fun1((4,4),3)

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

In [26]:
"""
2. Create a method that takes n Numpy arrays of same dimensions sums them and return the answer.
"""

def fun2():
    x=int(input("Enter Number of rows: "))
    y=int(input("Enter Number of columns: "))
    n=int(input("Enter Number to be filled with: "))
    arr=np.full((x,y),n)
    arr1=np.full((x,y),n)
    print("\nArray 1 \n",arr)
    print("\nArray 2 \n",arr1)
    print("\nSum of two arrays: \n",np.add(arr,arr1))

In [27]:
fun2()

Enter Number of rows: 2
Enter Number of columns: 3
Enter Number to be filled with: 5

Array 1 
 [[5 5 5]
 [5 5 5]]

Array 2 
 [[5 5 5]
 [5 5 5]]

Sum of two arrays: 
 [[10 10 10]
 [10 10 10]]


In [4]:
"""
3. Given a 2 D Array of N X M Dimension, Write a function that accepts this array as well as two numbers N and M. 
The method should return the top-left N X M sub matrix e.g:
[ [1, 2, 3], [4, 5, 6], [7, 8, 9], ] top_left_sub_matrix (matrix, 2, 2) -> should return: [ [1, 2] [4, 5] ]
"""

def fun3():
    n=int(input("How many numbers to be added into the array: "))
    i=0
    arr=[]
    for i in range(n):
        x=int(input("Enter the value: "))
        arr.append(x)
    print("Array values: ",arr)
    rows=int(input("How many rows: "))
    cols=int(input("How many cols: "))
    arr_reshape = np.reshape(arr,(rows,cols))
    print("\nArray\n",arr_reshape)
    top_left_sub_matrix=arr_reshape[0:2,0:2]
    print("\nTop left Sub Matrix\n",top_left_sub_matrix)

In [5]:
fun3()

How many numbers to be added into the array: 9
Enter the value: 1
Enter the value: 2
Enter the value: 3
Enter the value: 4
Enter the value: 5
Enter the value: 6
Enter the value: 7
Enter the value: 8
Enter the value: 9
Array values:  [1, 2, 3, 4, 5, 6, 7, 8, 9]
How many rows: 3
How many cols: 3

Array
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Top left Sub Matrix
 [[1 2]
 [4 5]]


In [19]:
"""
4. Given a 2 D Array of N X M Dimension, Write a function that accepts this array as well as two numbers N and M 
The method should return the bottom-right N X M sub matrix e.g.:
[ [1, 2, 3], [4, 5, 6], [7, 8, 9], ] sub_matrix(matrix, 1, 1) -> should return : 
(Keep in mind these arrays are zero indexed) [ [5, 6] [8, 9] ]
"""

def fun4():
    n=int(input("How many numbers to be added into the array: "))
    i=0
    arr=[]
    for i in range(n):
        x=int(input("Enter the value: "))
        arr.append(x)
    print("Array values: ",arr)
    rows=int(input("How many rows: "))
    cols=int(input("How many cols: "))
    arr_reshape = np.reshape(arr,(rows,cols))
    print("\nArray\n",arr_reshape)
    bottom_right_sub_matrix=arr_reshape[1:3,1:3]
    print("\nBottom-right Sub Matrix\n",bottom_right_sub_matrix)

In [20]:
fun4()

How many numbers to be added into the array: 9
Enter the value: 1
Enter the value: 2
Enter the value: 3
Enter the value: 4
Enter the value: 5
Enter the value: 6
Enter the value: 7
Enter the value: 8
Enter the value: 9
Array values:  [1, 2, 3, 4, 5, 6, 7, 8, 9]
How many rows: 3
How many cols: 3

Array
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Bottom-right Sub Matrix
 [[5 6]
 [8 9]]


In [36]:
"""
5. Given a 1 D Numpy Array. Write a function that accepts this array as parameters. 
The method should return a dictionary with 'mean' and 'std_dev' as key and array's mean and array's standard deviation as values:
[1, 1, 1] solution(arr) -> should return : {'mean': 1.0, 'std_dev': 0.0}
"""

def fun5():
    n=int(input("How many numbers to be added into the array: "))
    i=0
    arr=[]
    for i in range(n):
        x=int(input("Enter the value: "))
        arr.append(x)
    print("\nArray values: ",arr)
    arr_mean=np.mean(arr)
    arr_std_dev=np.std(arr)
    my_dic={'mean': arr_mean,
           'std_dev': arr_std_dev}
    print("\nThe Dictionary Value: ",my_dic)

In [37]:
fun5()

How many numbers to be added into the array: 6
Enter the value: 1
Enter the value: 2
Enter the value: 3
Enter the value: 4
Enter the value: 5
Enter the value: 6

Array values:  [1, 2, 3, 4, 5, 6]

The Dictionary Value:  {'mean': 3.5, 'std_dev': 1.707825127659933}
